USE [master]
GO

/****** Object:  Database [BlueHarborDb]    Script Date: 02/07/2026 15:08:08 ******/
CREATE DATABASE [BlueHarborDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlueHarborDb', FILENAME = N'/var/opt/mssql/data/BlueHarborDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlueHarborDb_log', FILENAME = N'/var/opt/mssql/data/BlueHarborDb_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlueHarborDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlueHarborDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlueHarborDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlueHarborDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlueHarborDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlueHarborDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlueHarborDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlueHarborDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlueHarborDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlueHarborDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlueHarborDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlueHarborDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlueHarborDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlueHarborDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlueHarborDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlueHarborDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BlueHarborDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlueHarborDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlueHarborDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlueHarborDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlueHarborDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlueHarborDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BlueHarborDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlueHarborDb] SET RECOVERY FULL 
GO

ALTER DATABASE [BlueHarborDb] SET  MULTI_USER 
GO

ALTER DATABASE [BlueHarborDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlueHarborDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlueHarborDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlueHarborDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BlueHarborDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlueHarborDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BlueHarborDb] SET QUERY_STORE = ON
GO

ALTER DATABASE [BlueHarborDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BlueHarborDb] SET  READ_WRITE 
GO

