// <auto-generated />
using BlueHarbor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueHarbor.Migrations
{
    [DbContext(typeof(BlueHarborDbContext))]
    partial class BlueHarborDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Berth", b =>
                {
                    b.Property<int>("BerthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BerthId"));

                    b.Property<string>("BerthName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("BerthId");

                    b.HasIndex("SizeId");

                    b.ToTable("Banchina", (string)null);

                    b.HasData(
                        new
                        {
                            BerthId = 1,
                            BerthName = "Berth XL1",
                            SizeId = 1
                        },
                        new
                        {
                            BerthId = 2,
                            BerthName = "Berth L1",
                            SizeId = 2
                        },
                        new
                        {
                            BerthId = 3,
                            BerthName = "Berth M1",
                            SizeId = 3
                        },
                        new
                        {
                            BerthId = 4,
                            BerthName = "Berth M2",
                            SizeId = 3
                        },
                        new
                        {
                            BerthId = 5,
                            BerthName = "Berth S1",
                            SizeId = 4
                        },
                        new
                        {
                            BerthId = 6,
                            BerthName = "Berth S2",
                            SizeId = 4
                        },
                        new
                        {
                            BerthId = 7,
                            BerthName = "Berth S3",
                            SizeId = 4
                        },
                        new
                        {
                            BerthId = 8,
                            BerthName = "Berth S4",
                            SizeId = 4
                        });
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.ListaNavi", b =>
                {
                    b.Property<int>("IdListaNavi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdListaNavi"));

                    b.Property<int>("FK_Id_Dimensione")
                        .HasColumnType("int");

                    b.Property<string>("NomeNave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdListaNavi");

                    b.HasIndex("FK_Id_Dimensione");

                    b.ToTable("ListaNavi", (string)null);

                    b.HasData(
                        new
                        {
                            IdListaNavi = 1,
                            FK_Id_Dimensione = 1,
                            NomeNave = "MSC Splendida"
                        },
                        new
                        {
                            IdListaNavi = 2,
                            FK_Id_Dimensione = 1,
                            NomeNave = "Costa Favolosa"
                        },
                        new
                        {
                            IdListaNavi = 3,
                            FK_Id_Dimensione = 2,
                            NomeNave = "Norwegian Epic"
                        },
                        new
                        {
                            IdListaNavi = 4,
                            FK_Id_Dimensione = 2,
                            NomeNave = "Celebrity Reflection"
                        },
                        new
                        {
                            IdListaNavi = 5,
                            FK_Id_Dimensione = 3,
                            NomeNave = "Queen Mary 2"
                        },
                        new
                        {
                            IdListaNavi = 6,
                            FK_Id_Dimensione = 3,
                            NomeNave = "Disney Dream"
                        },
                        new
                        {
                            IdListaNavi = 7,
                            FK_Id_Dimensione = 4,
                            NomeNave = "Seabourn Odyssey"
                        },
                        new
                        {
                            IdListaNavi = 8,
                            FK_Id_Dimensione = 4,
                            NomeNave = "Wind Star"
                        });
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Occupancy", b =>
                {
                    b.Property<int>("OccupancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OccupancyId"));

                    b.Property<int>("BerthId")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OccupancyId");

                    b.HasIndex("BerthId");

                    b.HasIndex("ShipId");

                    b.HasIndex("UserId");

                    b.ToTable("Occupazione", (string)null);
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Ruolo", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Operator"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Scheduler"
                        });
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Ship", b =>
                {
                    b.Property<int>("ShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipId"));

                    b.Property<int>("ArrivalDay")
                        .HasColumnType("int");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("IdListaNavi")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShipId");

                    b.HasIndex("IdListaNavi");

                    b.HasIndex("UserId");

                    b.ToTable("Nave", (string)null);
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeId");

                    b.ToTable("Dimensione", (string)null);

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            SizeName = "XL"
                        },
                        new
                        {
                            SizeId = 2,
                            SizeName = "L"
                        },
                        new
                        {
                            SizeId = 3,
                            SizeName = "M"
                        },
                        new
                        {
                            SizeId = 4,
                            SizeName = "S"
                        });
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.SystemState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDay = 1
                        });
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Utente", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@blueharbor.com",
                            Name = "Admin",
                            Password = "admin",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Berth", b =>
                {
                    b.HasOne("BlueHarbor.Domain.Entities.Size", "Size")
                        .WithMany("Berths")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Size");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.ListaNavi", b =>
                {
                    b.HasOne("BlueHarbor.Domain.Entities.Size", "Dimensione")
                        .WithMany("ListaNavi")
                        .HasForeignKey("FK_Id_Dimensione")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensione");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Occupancy", b =>
                {
                    b.HasOne("BlueHarbor.Domain.Entities.Berth", "Berth")
                        .WithMany("Occupancies")
                        .HasForeignKey("BerthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueHarbor.Domain.Entities.Ship", "Ship")
                        .WithMany("Occupancies")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueHarbor.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Berth");

                    b.Navigation("Ship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Ship", b =>
                {
                    b.HasOne("BlueHarbor.Domain.Entities.ListaNavi", "ListaNavi")
                        .WithMany("Navi")
                        .HasForeignKey("IdListaNavi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueHarbor.Domain.Entities.User", "User")
                        .WithMany("Ships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaNavi");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.User", b =>
                {
                    b.HasOne("BlueHarbor.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Berth", b =>
                {
                    b.Navigation("Occupancies");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.ListaNavi", b =>
                {
                    b.Navigation("Navi");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Ship", b =>
                {
                    b.Navigation("Occupancies");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.Size", b =>
                {
                    b.Navigation("Berths");

                    b.Navigation("ListaNavi");
                });

            modelBuilder.Entity("BlueHarbor.Domain.Entities.User", b =>
                {
                    b.Navigation("Ships");
                });
#pragma warning restore 612, 618
        }
    }
}
