CREATE DATABASE BlueHarbor;
GO

USE BlueHarbor;
GO

CREATE TABLE Role (
    RoleId INT PRIMARY KEY IDENTITY(1,1),
    RoleName VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Size (
    SizeId INT PRIMARY KEY IDENTITY(1,1),
    SizeName VARCHAR(2) NOT NULL CHECK (SizeName IN ('XL', 'L', 'M', 'S'))
);
GO

CREATE TABLE [User] (
    UserId INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    RoleId INT NOT NULL FOREIGN KEY REFERENCES Role(RoleId)
);
GO

CREATE TABLE Berth (
    BerthId INT PRIMARY KEY IDENTITY(1,1),
    BerthName VARCHAR(50) NOT NULL,
    SizeId INT NOT NULL FOREIGN KEY REFERENCES Size(SizeId)
);
GO

CREATE TABLE Ship (
    ShipId INT PRIMARY KEY IDENTITY(1,1),
    ShipName VARCHAR(100) NOT NULL,
    ArrivalDay INT NOT NULL,
    DurationDays INT NOT NULL,
    Status VARCHAR(10) NOT NULL CHECK (Status IN ('Pending', 'Assigned', 'Departed')),
    Notes VARCHAR(500),
    SizeId INT NOT NULL FOREIGN KEY REFERENCES Size(SizeId),
    UserId INT NOT NULL FOREIGN KEY REFERENCES [User](UserId)
);
GO

CREATE TABLE Occupancy (
    OccupancyId INT PRIMARY KEY IDENTITY(1,1),
    StartDay INT NOT NULL,
    ShipId INT NOT NULL FOREIGN KEY REFERENCES Ship(ShipId),
    BerthId INT NOT NULL FOREIGN KEY REFERENCES Berth(BerthId),
    UserId INT NOT NULL FOREIGN KEY REFERENCES [User](UserId)
);
GO